import 'package:get/get.dart';

class Messages extends Translations{

  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      // Step D
      'Home': 'Home',
      'Cart': 'Cart',
      'Search': 'Search',
      'Accept all the': 'Accept all the',
      'No Data Found': 'No Data Found',
      'Account': 'Account',
      'Product Category': 'Product Category',
      'Latest Product': 'Latest Product',
      'view all': 'View all',
      'Out of Stock': 'Out of Stock',
      'Cart Max Reach': 'Quantity Should Be less then @stock',
      'You have reached the maximum': 'You have exceeded the Maximum limit',
      'Added In Cart': 'Go to cart and checkout',
      'Service Unavailable': 'Product not delivered on this pincode @pinCode',
      'We have sent': 'We have sent an OTP on your email id @email',
      'vendor not serviceable': 'Vendor not serviceable @pinCode',
      'Edit Profile': 'Edit Profile',
      'Change Password': 'Change Password',
      'Payment History': 'Payment History',
      'Order History': 'Order History',
      'Logout': 'Logout',
      'Proceed To Checkout': 'Proceed To Checkout',
      'Reset Password Heading': 'Reset your password',
      'Reset Password Toolbar Title': 'Change Password',
      'Reset Password': 'Reset Password',
      'Category': 'Category',
      'Resend OTP': 'Resend OTP',
      'Verify-OTP': 'Verify-OTP',
      'Go to login': 'Go to login',
      'Api Failure': 'Something went wrong',
      'OTP Send Failed': 'OTP Send Failed',
      'Accept all terms & conditions': 'Accept all terms & conditions',

      // Step C
      'Enter Phone Number': 'Enter Phone Number',
      'Enter Email': 'Enter Email',
      'Enter Valid Email': 'Enter Valid Email',
      'Enter first name': 'Enter first name',
      'Enter last name': 'Enter last name',
      'First Name': 'First Name',
      'Last Name': 'Last Name',
      'Enter Name': 'Enter Name',
      'Enter phone number': 'Enter phone number',
      'Number': 'Number',
      'Address Details': 'Address Details',
      'Enter Valid pin-code': 'Enter Valid pin-code',
      'Enter Pin-Code': 'Enter Pin-Code',
      'Enter city': 'Enter city name',
      'Help & Support': 'Help & Support',
      'Checkout Cart': 'Checkout Cart',
      'Order now': 'Order now',
      'Rating': 'Rating',
      'Review and rating': 'Customer Review and Comments',
      'Related Product': 'Similar products',

      'Order Summary': 'Order Summary',
      'Total Gst Applied': 'Total GST',
      'Total Discount Applied': 'Total Discount',
      'Sub Total Amount': 'Sub Total',
      'Delivery Charge': 'Total Delivery Charge',
      'Payable amount': 'Payable amount',
      'Grand Total': 'Grand Total',

      'Total Amount': 'Total Amount',
      'AddToCart': 'Add To Basket',

      'Forgot Password': 'Forgot Password',

      // Step B
      'Address': 'Address',
      'Verify Email Address': 'Verify Email Address',
      'Submit': 'Submit',
      'Support': 'Support',
      'Need Help': 'Need Help?',
      'Support Message': 'Any problem please fill your problem, we will solve soon.',
      'Subject': 'Subject',
      'Your Query': 'Your Query',
      'Default Address': 'Default Address',
      'Another Place': 'Another Place',
      'Delivery Address': 'Delivery Address',
      'City': 'City',
      'Try Again': 'Try Again',
      'City Name': 'City Name',
      'Choose option': 'Choose Option',
      'Gallery': 'Gallery',
      'Camera': 'Camera',
      'Get OTP': 'Get OTP',
      'Update Profile': 'Update Profile',
      'Pin-Code': 'Pin-Code',
      'Have remembered': 'Have remembered?',
      "Don't Have a Account": "Don't Have a Account?",
      "You Have a Account": "You Have a Account?",
      'Forgot Your Password': 'Forgot Your Password',
      'Forgot Message': 'Don`t worry just verify your email and got a passwords',

      // Step A
      'Enter Password' : "Enter password",
      'Enter Delivery Address' : "Enter Delivery Address",
      'Password' : "Password",
      'Confirm Password' : "Confirm Password",
      'Notification' : "Notification",
      'Proceed' : "Proceed",
      'Pay Now' : "Pay Now",
      'Cash on delivery' : "Cash on delivery",
      'Order Detail' : "Order Detail",
      'Delivery Details' : "Delivery Details",
      'Delivery Location' : "Delivery Location",
      'Contact Detail' : "Contact Detail",
      'Amount Summary' : "Amount Summary",
      'Discount Apply' : "Discount Apply",
      'Discount Applied' : "Discount Applied",
      'GST Apply' : "GST Apply",
      'GST Applied' : "GST Applied",
      'Delivery Fee' : "Delivery Fee",
      'Order Amount' : "Order Amount",
      'Payment Status' : "Payment Status",
      'Payment Mod' : "Payment Mod",
      'Product Details' : "Product Details",
      'Password Successfully changed' : "Password Successfully changed",
      'Please Enter Password' : "Please Enter Password",
      'Password and Confirm Password Mismatched' : "Password and Confirm Password Mismatched",
      'Enter Confirm Password' : "Enter Confirm Password",
      'Password must be 4 characters' : "Password must be 4 characters",
      'My Complain' : "My Complain",
    },
    'hi_IN': {
      // Step D
      'Home': 'होम',
      'Cart': 'कार्ट',
      'Search': 'खोजें',
      'Accept all the': 'सभी को स्वीकार करें',
      'No Data Found': 'कोई डेटा नहीं मिला',
      'Account': 'खाता',
      'Product Category': 'उत्पाद श्रेणी',
      'Latest Product': 'नवीनतम उत्पाद',
      'view all': 'सभी देखें',
      'Out of Stock': 'स्टॉक में नहीं',
      'Added In Cart': 'कार्ट में जाएं और चेकआउट करें',
      'Service Unavailable': 'सेवा उपलब्ध नहीं है पिन-कोड @pinCode के लिए',
      'We have sent': 'हमने आपके ईमेल @email पर एक OTP भेजा है',
      'vendor not serviceable': 'विक्रेता सेवा के योग्य नहीं है पिन-कोड @pinCode के लिए',
      'Edit Profile': 'प्रोफ़ाइल संपादित करें',
      'Change Password': 'पासवर्ड बदलें',
      'Payment History': 'भुगतान इतिहास',
      'Order History': 'खरीदारी इतिहास',
      'Logout': 'लॉगआउट',
      'Proceed To Checkout': 'चेकआउट करें',
      'Reset Password Heading': 'अपना पासवर्ड रीसेट करें',
      'Reset Password Toolbar Title': 'पासवर्ड बदलें',
      'Reset Password': 'पासवर्ड रीसेट करें',
      'Category': 'श्रेणी',
      'Resend OTP': 'OTP फिर से भेजें',
      'Verify-OTP': 'OTP सत्यापित करें',
      'Go to login': 'लॉगिन पर जाएं',
      'Api Failure': 'कुछ गड़बड़ हो गई है',
      'OTP Send Failed': 'OTP भेजने में विफल',
      'Accept all terms & conditions': 'सभी नियम और शर्तें स्वीकार करें',

      // Step C
      'Enter Phone Number': 'फ़ोन नंबर दर्ज करें',
      'Enter Email': 'ईमेल दर्ज करें',
      'Enter Valid Email': 'वैध ईमेल दर्ज करें',
      'Enter first name': 'पहला नाम दर्ज करें',
      'Enter last name': 'अंतिम नाम दर्ज करें',
      'First Name': 'पहला नाम',
      'Last Name': 'अंतिम नाम',
      'Enter Name': 'नाम दर्ज करें',
      'Enter phone number': 'फ़ोन नंबर दर्ज करें',
      'Number': 'नंबर',
      'Address Details': 'पता विवरण',
      'Enter Valid pin-code': 'वैध पिन कोड दर्ज करें',
      'Enter Pin-Code': 'पिन कोड दर्ज करें',
      'Enter city': 'शहर नाम दर्ज करें',
      'Help & Support': 'मदद और सहायता',
      'Checkout Cart': 'कार्ट चेकआउट',
      'Order now': 'अभी ख़रीदे',
      'Order Summary': 'खरीदारी सारांश',
      'Total Amount': 'कुल राशि',
      'Total Gst': 'कुल जीएसटी',
      'Total Discount': 'कुल डिस्काउंट',
      'Total Delivery Charge': 'कुल वितरण शुल्क',
      'Grand Total': 'कुल योग',
      'Forgot Password': 'पासवर्ड भूल गए',

      // Step B
      'Address': 'पता',
      'Verify Email Address': 'ईमेल पता सत्यापित करें',
      'Submit': 'प्रस्तुत',
      'Support': 'सहायता',
      'Need Help': 'मदद चाहिए?',
      'Support Message': 'कोई समस्या हो तो कृपया अपनी समस्या भरें, हम जल्द ही हल करेंगे।',
      'Subject': 'विषय',
      'Your Query': 'आपका प्रश्न',
      'Default Address': 'डिफ़ॉल्ट पता',
      'Another Place': 'दूसरा स्थान',
      'Delivery Address': 'वितरण पता',
      'City': 'शहर',
      'Try Again': 'पुनः प्रयास करें',
      'City Name': 'शहर का नाम',
      'Choose option': 'विकल्प चुनें',
      'Gallery': 'गैलरी',
      'Camera': 'कैमरा',
      'Get OTP': 'OTP प्राप्त करें',
      'Update Profile': 'प्रोफ़ाइल अपडेट करें',
      'Pin-Code': 'पिन कोड',
      'Have remembered': 'याद रखा है?',
      "Don't Have a Account": "खाता नहीं है?",
      "You Have a Account": "आपका खाता है?",
      'Forgot Your Password': 'क्या आपने पासवर्ड भूल गए हैं',
      'Forgot Message': 'चिंता न करें, बस अपना ईमेल सत्यापित करें और पासवर्ड प्राप्त करें',

      // Step A
      'Enter Password': "पासवर्ड दर्ज करें",
      'Enter Delivery Address': "वितरण पता दर्ज करें",
      'Password': "पासवर्ड",
      'Confirm Password': "पासवर्ड की पुष्टि करें",
      'Notification': "सूचना",
      'Proceed': "आगे बढ़ें",
      'Pay Now': "अभी भुगतान करें",
      'Cash on delivery': "डिलीवरी पर नकदी",
      'Order Detail': "आदेश का विवरण",
      'Delivery Details': "वितरण का विवरण",
      'Delivery Location': "वितरण स्थान",
      'Contact Detail': "संपर्क विवरण",
      'Amount Summary': "राशि सारांश",
      'Discount Apply': "छूट लागू करें",
      'GST Apply': "जीएसटी लागू करें",
      'Order Amount': "आदेश राशि",
      'Payment Status': "भुगतान स्थिति",
      'Payment Mod': "भुगतान विधि",
      'Product Details': "उत्पाद विवरण",
      'Password Successfully changed': "पासवर्ड सफलतापूर्वक बदला गया",
      'Please Enter Password': "कृपया पासवर्ड दर्ज करें",
      'Password and Confirm Password Mismatched': "पासवर्ड और पासवर्ड की पुष्टि मेल नहीं खाते",
      'Enter Confirm Password': "पासवर्ड की पुष्टि दर्ज करें",
      'Password must be 4 characters': "पासवर्ड 4 अक्षरों का होना चाहिए",
    }
  };

}